CREATE TABLE Class (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	InstructorId INT NOT NULL
		FOREIGN KEY REFERENCES Instructor (InstructorId) ON DELETE CASCADE ON UPDATE CASCADE,
	DepartmentId INT NOT NULL
		FOREIGN KEY REFERENCES Department (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	CourseName NVARCHAR(30) NOT NULL,
	CourseDescription NVARCHAR(150) NOT NULL,
	CourseCapacity INT NOT NULL CHECK (CourseCapacity > 0),
	StartTime DATE NOT NULL,
	EndTime DATE NOT NULL,
	BuildingId INT NOT NULL
		FOREIGN KEY REFERENCES Building (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	RoomNumber NVARCHAR(30) NOT NULL,
);

CREATE TABLE Person (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(30) NOT NULL,
	Email NVARCHAR(255) NOT NULL UNIQUE,
);

CREATE TABLE Department (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(150) NOT NULL,
	DeanId INT NOT NULL
		FOREIGN KEY REFERENCES Instructor (InstructorId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Building (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	BuildingName NVARCHAR(150) NOT NULL
);


CREATE TABLE Enrollment (
	CourseId INT NOT NULL,
	StudentId INT NOT NULL,
	PRIMARY KEY (CourseId, StudentId)
);

CREATE TABLE Instructor (
	DepartmentId INT NOT NULL, 
	InstructorId INT NOT NULL 
);

CREATE TABLE Transcript (
	PersonId INT NOT NULL,
	CourseId INT NOT NULL,
	Grade NVARCHAR(30) NOT NULL,
	PRIMARY KEY (PersonId, CourseId)
);

CREATE TABLE Admin (
	AdminId INT NOT NULL PRIMARY KEY IDENTITY
);